language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository

script:
   - ./gradlew build connectedAndroidTest
