sudo: required
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.1.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-16
  licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

before_script:

  - ( while [ 1 ]; do sleep 5; echo y; done ) | android update sdk --no-ui --all --filter build-tools-25.0.1,android-25,extra-android-m2repository
# Build Tools 24.0.1
#  - ( while [ 1 ]; do sleep 5; echo y; done ) | android update sdk --no-ui --all --filter build-tools-24.0.1,android-24,extra-android-m2repository
# Build Tools 23.0.1
#  - ( while [ 1 ]; do sleep 5; echo y; done ) | android update sdk --no-ui --all --filter build-tools-23.0.1,android-23,extra-android-m2repository

  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 10
  - adb shell input keyevent 82

script:
#   - ./gradlew connectedAndroidTest --stacktrace --debug --info
   - ./gradlew build connectedCheck --stacktrace --debug --info
#after_success:
#  - ./gradlew crashlyticsUploadDistributionDebug
#  - mkdir -p app/build/reports/jacoco/test/
#  - cp app/build/reports/coverage/debug/report.xml app/build/reports/jacoco/test/jacocoTestReport.xml
#  - ./gradlew coveralls
after_failure:
    - "pwd"
    - "ls -la"
#notifications:
#
#  slack: